# Generated by Django 5.0.2 on 2024-02-29 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_password_options_alter_password_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='password',
            new_name='encrypted_password',
        ),
    ]
