# Generated by Django 5.0.2 on 2024-02-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_remove_password_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='key',
            field=models.CharField(default='', max_length=255),
        ),
    ]
