# Generated by Django 5.0.2 on 2024-02-29 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_password_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='password',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='password',
            name='encrypted_password',
        ),
        migrations.RemoveField(
            model_name='password',
            name='key',
        ),
        migrations.AddField(
            model_name='password',
            name='logo',
            field=models.CharField(default='logo', max_length=300),
        ),
        migrations.AddField(
            model_name='password',
            name='password',
            field=models.CharField(default='[assword]', max_length=200),
        ),
        migrations.AlterField(
            model_name='password',
            name='email',
            field=models.CharField(default='dinesh@gmail.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='password',
            name='name',
            field=models.CharField(default='dinesh', max_length=100),
        ),
        migrations.AlterField(
            model_name='password',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
